// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH3kFtVl3S-Qs4wu8VTlh9364-91O662w',
    appId: '1:1001946654450:web:87114e37d53336a538d26b',
    messagingSenderId: '1001946654450',
    projectId: 'chat-app-d5e59',
    authDomain: 'chat-app-d5e59.firebaseapp.com',
    storageBucket: 'chat-app-d5e59.firebasestorage.app',
    measurementId: 'G-MWRRRTQZVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYksPltD2U0-htUyO6s4om5Zhg3FIarOU',
    appId: '1:1001946654450:android:ebe6fd57a5f35e2738d26b',
    messagingSenderId: '1001946654450',
    projectId: 'chat-app-d5e59',
    storageBucket: 'chat-app-d5e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0224P3rno4vrr0-CAx9qEja0wdJ_zbww',
    appId: '1:1001946654450:ios:eb7e98056d1538bb38d26b',
    messagingSenderId: '1001946654450',
    projectId: 'chat-app-d5e59',
    storageBucket: 'chat-app-d5e59.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0224P3rno4vrr0-CAx9qEja0wdJ_zbww',
    appId: '1:1001946654450:ios:eb7e98056d1538bb38d26b',
    messagingSenderId: '1001946654450',
    projectId: 'chat-app-d5e59',
    storageBucket: 'chat-app-d5e59.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH3kFtVl3S-Qs4wu8VTlh9364-91O662w',
    appId: '1:1001946654450:web:2e641dac8c23970738d26b',
    messagingSenderId: '1001946654450',
    projectId: 'chat-app-d5e59',
    authDomain: 'chat-app-d5e59.firebaseapp.com',
    storageBucket: 'chat-app-d5e59.firebasestorage.app',
    measurementId: 'G-87WDTQHTDJ',
  );
}
